### ISSUE TITLE
Perplexity pages support

### ISSUE THREAD

**Issue by Toocky** [Hugo-COLLIN/SaveMyPhind-conversation-exporter#112]
Hi Mate,

Love your extension, and would love to see it extended to perplexity pages.

**Comment by Hugo-COLLIN** [comment]
Hey @Toocky,
You just made me discover this new Perplexity feature. I can’t test it yet, but I’ll be happy to implement the export when Pages are available to me.

![image](https://github.com/Hugo-COLLIN/SaveMyPhind-conversation-exporter/assets/101000595/69e8757e-232f-4e84-bc8b-ffcbef310922)

**Comment by Hugo-COLLIN** [comment]
Thank you for the discovery ! 

I will add it to the stack of things I want to export 🙃

**Comment by Hugo-COLLIN** [comment]
Finally done @Toocky !
You can confirm that it works when you receive the update 🙂

**Comment by Toocky** [comment]
@Hugo-COLLIN 

This is great, Thanks a lot for this.
