### ISSUE TITLE
Error when [ brackets ] are used in the article title - in Perplexity.AI - confuses it with the markdown

### ISSUE THREAD

**Issue by Teamsuccess2024** [Hugo-COLLIN/SaveMyPhind-conversation-exporter#119]
Example:

<div class="line-clamp-2 grow text-left default font-sans text-base text-textMain dark:text-textMainDark selection:bg-super/50 selection:text-textMain dark:selection:bg-superDuper/10 dark:selection:text-superDark"><span class="light font-sans text-base font-medium text-textOff dark:text-textOffDark selection:bg-super/50 selection:text-textMain dark:selection:bg-superDuper/10 dark:selection:text-superDark">**13.</span> [PDF] Jordan and the Palestinian Cause - Konrad-Adenauer-Stiftung**</div>

Error when [ brackets ] are used in the article title - in Perplexity.AI - confuses it with the markdown

It makes it into this - which is invalid md
- [PDF] Jordan and the Palestinian Cause - Konrad-Adenauer-Stiftung](https://www.kas.de/documents/268421/16446927/Jordan%2Band%2Bthe%2BPalestinian%2BCause.pdf/637518a0-7cf3-066f-caeb-ecd0a8788b49?t=1664645271140&version=1.0)

It just needs to remove, in this case, the 1st "]" to the right of PDF - to be valid markdown.

FYI Thanks for the great work!

**Comment by Hugo-COLLIN** [comment]
Thank you for the report @Teamsuccess2024 !
Could you provide the corresponding Perplexity thread so I can try to solve the bug ?
