### ISSUE TITLE
Perplexity Pages is broken

### ISSUE THREAD

**Issue by Toocky** [Hugo-COLLIN/SaveMyPhind-conversation-exporter#144]
Looks like pages exporting is broken. 

doesnt pull any of the content 

![image](https://github.com/user-attachments/assets/d1ba3527-1473-4b41-8412-3ce3a9d46f32)

![image](https://github.com/user-attachments/assets/dc7c599e-e328-4ca9-80f7-4eefd322b3ed)

**Comment by Hugo-COLLIN** [comment]
Hey @Toocky,
I just fixed it in #143. I'll publish v2.9.6 in the next few hours. 
Let me know when you receive the update.
