### ISSUE TITLE
Perplexity conversation export in .md file is duplicated in 2.9.6

### ISSUE THREAD

**Issue by Luke717** [Hugo-COLLIN/SaveMyPhind-conversation-exporter#148]
Hi Hugo. Nice work with this Chrome extension! I just saw the 2.9.6 update in my browser. But if I export a conversation from Perplexity, it appears twice - attached is a file from an export where you can see the duplication. I've tested 5 separate conversations as exports, and the duplicated content appears each time.

I hope this is an easy fix! I'm running the extension in Chrome for Windows 11 version 127.0.6533.119 (Official Build) (64-bit). Let me know if there's any other information you need.

Thanks!
Neville.
[2024-08-14_09-19-19_Perplexity.ai_How do I install Meta's Lama 3 on my Windows desktop PC.md](https://github.com/user-attachments/files/16609884/2024-08-14_09-19-19_Perplexity.ai_How.do.I.install.Meta.s.Lama.3.on.my.Windows.desktop.PC.md)

**Comment by Hugo-COLLIN** [comment]
Hi @Luke717,
Thank you for mentioning this bug. 
Really strange it happens now as I didn't change this part of the code. I tested on previous versions of the extension and it's also doing the same, on Perplexity Search only. Perplexity certainly changed something.
I will investigate.

**Comment by Hugo-COLLIN** [comment]
Hi again @Luke717,
I just published v2.9.7 that solves the bug. Please let me know if it works properly for you when you receive the update 🙂

**Comment by Luke717** [comment]
Hi @Hugo-COLLIN

With 2.9.7. now installed in Chrome, I just tried it, and problem solved! It works perfectly without duplicated content. Thanks for fixing it so fast 🚀
