### ISSUE TITLE
Phind doesn't work on normal Threads

### ISSUE THREAD

**Issue by ArtieFuzzz** [Hugo-COLLIN/SaveMyPhind-conversation-exporter#16]
Recently Phind has made Basic Search the default search mode, trying to export a Basic Search thread doesn't seem to be possible and it just errors.

Example URL: https://www.phind.com/search?cache=gai4zhts09ggbvoftxmxve48

**Comment by Hugo-COLLIN** [comment]
@ArtieFuzzz Thank you for your feedback!
Just fixed that on #18 and published a new release. You can wait the store update or download it here (it's not updated automatically if you manually install the extension) : https://github.com/Hugo-COLLIN/SaveMyPhind-conversation-exporter/releases/tag/v1.9.18
