### ISSUE TITLE
SMC does not save text before lists in Perplexity

### ISSUE THREAD

**Issue by TerEsper** [Hugo-COLLIN/SaveMyPhind-conversation-exporter#176]
Save my chatbot does not save text in Perplexity, that is written before first list in AI's answer

Here's an example of this problem: https://www.perplexity.ai/search/how-can-i-solve-5x-2-20x-20-0-Hr9d.5rCRJKgb9zRqZFLXw
![изображение](https://github.com/user-attachments/assets/0fb794da-627a-4d19-9294-50485a916931)

When I try to save it, I get the next file:
[2024-09-09_12-31-10_Perplexity.ai_how can i solve 5x^2 + 20x + 20 = 0.md](https://github.com/user-attachments/files/16928531/2024-09-09_12-31-10_Perplexity.ai_how.can.i.solve.5x.2.%2B.20x.%2B.20.0.md)

![изображение](https://github.com/user-attachments/assets/ab21b1be-828d-4350-a075-1c850b6bbfb9)

The text, that is written before the first list in every AI answer, is just ignored. In this case it is not something important, but sometimes it can be. 

UPD: Extension version: 3.2.0, Last update: 8 spt 2024, Firefox

**Comment by Hugo-COLLIN** [comment]
@TerEsper Thank you for mentioning this issue. 
It should be solved in the next update, please let me know 🙂.
