### ISSUE TITLE
LateX not properly formatted in export (ChatGPT, Perplexity, Phind)

### ISSUE THREAD

**Issue by Hugo-COLLIN** [Hugo-COLLIN/SaveMyPhind-conversation-exporter#185]
Examples:
- https://chatgpt.com/c/66f27f0d-253c-8008-b380-b4ab5a25b333
- https://www.perplexity.ai/search/write-complex-equations-using-UW.V4PRASxexijwFNSAwZA
- https://www.phind.com/agent?cache=cm2i7cjt1000amc0c3kpdzigc

![image](https://github.com/user-attachments/assets/0901b6c4-f36e-4d22-960e-0973a77ada31)

![image](https://github.com/user-attachments/assets/c31e1c52-c85d-40ed-8113-e1af7714e92d)

**Comment by sfd99** [comment]
Yes, Hugo - 

please do fix the MATH LATEX expressions
in PERPLEXITY-generated MD files.

Save my Chat is a great, useful extension 
for my PERPLEXITY threads.
But I use  a lot of Calculus math expressions,
and it's important to keep the original LATEX expressions... 

Thanks/Merci!
**SFD99
San Francisco.**

**Comment by Hugo-COLLIN** [comment]
Hey @sfd99,
It's now done !
Please let me know it works for you when you receive the update.

**Comment by sfd99** [comment]
Save my Chatbot ext. in my Chrome/Linux
 shows as version: ==> 3.4.0
Is that the latest version?
How do I update to your new LATEX-ok version?.
_Thanks Hugo!._

**Comment by Hugo-COLLIN** [comment]
@sfd99 Yes, v3.40 is the latest version with LaTeX support

**Comment by sfd99** [comment]
Ah, perfect 
- thanks Hugo!.
