### ISSUE TITLE
Missing newline before Source sections in Perplexity

### ISSUE THREAD

**Issue by heseber** [Hugo-COLLIN/SaveMyPhind-conversation-exporter#186]
When exporting from Perplexity, the last paragraph of an answer is usually followed by a horizontal line (`---`) and the source section section that begins on the subsequent line with `**Source:**`. There is a missing empty line preceding the `---` line - the last paragraph of the answer is followed directly by the `---` line. Therefore, the last paragraph is interpreted as an H2 headline and not as a standard paragraph. I wrote a short script to fix this, but it would be helpful if you added an extra newline between the last paragraph of the response and the `---` line.

Just for illustration purposes, here is my script for fixing the issue:

```python
#!/usr/bin/env python
import sys
import os

def process_text(input_file):
    with open(input_file, 'r') as infile:
        lines = infile.readlines()
    with open(input_file, 'w') as outfile:
        for i in range(len(lines)):
            if lines[i].strip() == '---' and (i + 1 < len(lines) and lines[i + 1].startswith('**Sources:**')):
                outfile.write('\n')  # Add an extra newline before the '---' line
            outfile.write(lines[i])  # Write the current line to the output file

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {os.path.basename(sys.argv[0])} <input_file>")
        sys.exit(1)
    input_file = sys.argv[1]
    process_text(input_file)
```

**Comment by Hugo-COLLIN** [comment]
Nice workaround !
Just made the change in #188, please let me know when you receive the update.

**Comment by heseber** [comment]
Thanks for the fix, and sorry for the late reply. Yes, the update fixed this issue, thanks again!
