### ISSUE TITLE
Horizontal rule above "Sources:" requires \n 

### ISSUE THREAD

**Issue by adiba** [Hugo-COLLIN/SaveMyPhind-conversation-exporter#187]
https://github.com/Hugo-COLLIN/SaveMyPhind-conversation-exporter/blob/03b017685853131da06023948f186a6ea1b4a784/src/scripts/content/export/extractor/extractSources.js#L5

The string should start with two `\n`, otherwise preceding text will be treated as heading.

**Comment by Hugo-COLLIN** [comment]
Thank you for mentioning this bug.
Your feedback is joining #186. I just made the change in #188, please let me know when you receive the update.
