### ISSUE TITLE
Not working in Chatgpt on Chrome

### ISSUE THREAD

**Issue by Rumikern** [Hugo-COLLIN/SaveMyPhind-conversation-exporter#200]
Not working at all when I bring up Chatgpt. Works fine on Perplexity on Chrome. Is it supposed to with chatgpt?

Hopefully screen shot shows your icon - just shows as a white box with a grey down arrow. doesn't change when I open gpt or start a new chat. 

thanks for looking into. Has been invaluable for importing Perplexity chats into Scrivener. 

Kernan
<img width="88" alt="Screenshot 2024-10-29 at 4 59 24 PM" src="https://github.com/user-attachments/assets/888cf10a-da1c-4a12-9671-910fcaae7760">

**Comment by Rumikern** [comment]
I mentioned I'd send you how I use savemychatbot in scrivener. Here's an example of one chat series. 
2 pics of how I used savemychatbot for import to scrivener. one shot - had to capture with my phone to capture the drop down file menu - allows you to import and split a md file. the other pic shows what it looks like after split, all the individual chats neatly imported in sequence.  In that one scrivener project (where I keep all my chats), I can now do a search on terms across all my diverse chats. 
Thanks for creating it!
![IMG_5587](https://github.com/user-attachments/assets/97edf387-2513-4048-8783-6bacb34d58d9)
<img width="1456" alt="Screenshot 2024-10-29 at 5 07 52 PM" src="https://github.com/user-attachments/assets/dfca47dd-f116-43f9-9412-cd16e4fcd5ee">

**Comment by Hugo-COLLIN** [comment]
@Rumikern Thank you for mentioning this bug.
- Are your chat URLs different than `https://chatgpt.com/c/<unique-id>` or `https://chatgpt.com/share/<unique-id>`?
- Is there an error when you click on the icon (a popup, or in the developer console - type Cmd +Option +J)?

**Comment by Hugo-COLLIN** [comment]
@Rumikern Thank you so much for taking time to share your use case

**Comment by Hugo-COLLIN** [comment]
@Rumikern Is it working now?
