### ISSUE TITLE
perplexity export consistency

### ISSUE THREAD

**Issue by SIG-Labo** [Hugo-COLLIN/SaveMyPhind-conversation-exporter#65]
on perplexity i was able to get it to work the first couple of times , however eventually when i try to export using perplexity i get this:

# perplexity query here
Exported on 16/03/2024 at 16:03:07 [from Perplexity.ai](https://www.perplexity.ai/search/blablaurlhere) - with [SaveMyChatbot](https://save.hugocollin.com)

and thats it ! its missing all the text and reference urls. while  before it worked fine. 
i disabled chrome addons, cleared browser, nothing helped
tried firefox too, and firefox didnt work either

**Comment by Hugo-COLLIN** [comment]
@SIG-Labo Thank you for reporting 🙂
